


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admin" (
    "UUID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "Role" "text" DEFAULT 'Student'::"text" NOT NULL,
    "Password" "text" NOT NULL,
    "StaffID" "text",
    "StudentID" "text"
);


ALTER TABLE "public"."admin" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."question" (
    "QID" bigint NOT NULL,
    "QText" "text",
    "TopicID" bigint
);


ALTER TABLE "public"."question" OWNER TO "postgres";


ALTER TABLE "public"."question" ALTER COLUMN "QID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_QID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."resolution" (
    "ResID" bigint NOT NULL,
    "ResAt" timestamp with time zone DEFAULT "now"(),
    "ResText" "text",
    "ResURL" "text",
    "StaffID" "text",
    "SubmissionID" bigint NOT NULL
);


ALTER TABLE "public"."resolution" OWNER TO "postgres";


ALTER TABLE "public"."resolution" ALTER COLUMN "ResID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."resolution_ResID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."staff" (
    "UUID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "StaffID" "text" NOT NULL,
    "Division" "text",
    "StaffName" "text",
    "Password" "text"
);


ALTER TABLE "public"."staff" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."student" (
    "UUID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "StudentID" "text" NOT NULL,
    "StudentName" "text",
    "Year" integer DEFAULT 1,
    "Department" "text" DEFAULT ''::"text",
    "Password" "text" NOT NULL
);


ALTER TABLE "public"."student" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."submission" (
    "SubmissionID" bigint NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Status" "text",
    "StudentID" "text",
    "StaffID" "text",
    "TopicID" bigint
);


ALTER TABLE "public"."submission" OWNER TO "postgres";


ALTER TABLE "public"."submission" ALTER COLUMN "SubmissionID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."submission_SubmissionID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."topic" (
    "TopicID" bigint NOT NULL,
    "Tname" "text" NOT NULL
);


ALTER TABLE "public"."topic" OWNER TO "postgres";


ALTER TABLE "public"."topic" ALTER COLUMN "TopicID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."topic_TopicID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_answer" (
    "UAID" bigint NOT NULL,
    "AnswerText" "text",
    "QID" bigint NOT NULL,
    "SubmissionID" bigint NOT NULL,
    "AnsURL" "text"
);


ALTER TABLE "public"."user_answer" OWNER TO "postgres";


ALTER TABLE "public"."user_answer" ALTER COLUMN "UAID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_answer_UAID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_StaffID_key" UNIQUE ("StaffID");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_StudentID_key" UNIQUE ("StudentID");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_pkey" PRIMARY KEY ("UUID");



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_pkey" PRIMARY KEY ("QID");



ALTER TABLE ONLY "public"."resolution"
    ADD CONSTRAINT "resolution_pkey" PRIMARY KEY ("ResID");



ALTER TABLE ONLY "public"."staff"
    ADD CONSTRAINT "staff_StaffID_key" UNIQUE ("StaffID");



ALTER TABLE ONLY "public"."staff"
    ADD CONSTRAINT "staff_pkey" PRIMARY KEY ("UUID");



ALTER TABLE ONLY "public"."student"
    ADD CONSTRAINT "student_StudentID_key" UNIQUE ("StudentID");



ALTER TABLE ONLY "public"."student"
    ADD CONSTRAINT "student_pkey" PRIMARY KEY ("UUID");



ALTER TABLE ONLY "public"."submission"
    ADD CONSTRAINT "submission_pkey" PRIMARY KEY ("SubmissionID");



ALTER TABLE ONLY "public"."topic"
    ADD CONSTRAINT "topic_pkey" PRIMARY KEY ("TopicID");



ALTER TABLE ONLY "public"."user_answer"
    ADD CONSTRAINT "user_answer_pkey" PRIMARY KEY ("UAID");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_StaffID_fkey" FOREIGN KEY ("StaffID") REFERENCES "public"."staff"("StaffID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_StudentID_fkey" FOREIGN KEY ("StudentID") REFERENCES "public"."student"("StudentID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_TopicID_fkey" FOREIGN KEY ("TopicID") REFERENCES "public"."topic"("TopicID") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."resolution"
    ADD CONSTRAINT "resolution_StaffID_fkey" FOREIGN KEY ("StaffID") REFERENCES "public"."staff"("StaffID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."resolution"
    ADD CONSTRAINT "resolution_SubmissionID_fkey" FOREIGN KEY ("SubmissionID") REFERENCES "public"."submission"("SubmissionID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."submission"
    ADD CONSTRAINT "submission_StaffID_fkey" FOREIGN KEY ("StaffID") REFERENCES "public"."staff"("StaffID") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."submission"
    ADD CONSTRAINT "submission_StudentID_fkey" FOREIGN KEY ("StudentID") REFERENCES "public"."student"("StudentID") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."submission"
    ADD CONSTRAINT "submission_TopicID_fkey" FOREIGN KEY ("TopicID") REFERENCES "public"."topic"("TopicID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_answer"
    ADD CONSTRAINT "user_answer_QID_fkey" FOREIGN KEY ("QID") REFERENCES "public"."question"("QID") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."user_answer"
    ADD CONSTRAINT "user_answer_SubmissionID_fkey" FOREIGN KEY ("SubmissionID") REFERENCES "public"."submission"("SubmissionID") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."admin" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."question" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."resolution" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."staff" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."student" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."submission" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."topic" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_answer" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";



GRANT ALL ON TABLE "public"."admin" TO "anon";
GRANT ALL ON TABLE "public"."admin" TO "authenticated";
GRANT ALL ON TABLE "public"."admin" TO "service_role";



GRANT ALL ON TABLE "public"."question" TO "anon";
GRANT ALL ON TABLE "public"."question" TO "authenticated";
GRANT ALL ON TABLE "public"."question" TO "service_role";



GRANT ALL ON SEQUENCE "public"."question_QID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."question_QID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."question_QID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."resolution" TO "anon";
GRANT ALL ON TABLE "public"."resolution" TO "authenticated";
GRANT ALL ON TABLE "public"."resolution" TO "service_role";



GRANT ALL ON SEQUENCE "public"."resolution_ResID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."resolution_ResID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."resolution_ResID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."staff" TO "anon";
GRANT ALL ON TABLE "public"."staff" TO "authenticated";
GRANT ALL ON TABLE "public"."staff" TO "service_role";



GRANT ALL ON TABLE "public"."student" TO "anon";
GRANT ALL ON TABLE "public"."student" TO "authenticated";
GRANT ALL ON TABLE "public"."student" TO "service_role";



GRANT ALL ON TABLE "public"."submission" TO "anon";
GRANT ALL ON TABLE "public"."submission" TO "authenticated";
GRANT ALL ON TABLE "public"."submission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."submission_SubmissionID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."submission_SubmissionID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."submission_SubmissionID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."topic" TO "anon";
GRANT ALL ON TABLE "public"."topic" TO "authenticated";
GRANT ALL ON TABLE "public"."topic" TO "service_role";



GRANT ALL ON SEQUENCE "public"."topic_TopicID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."topic_TopicID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."topic_TopicID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_answer" TO "anon";
GRANT ALL ON TABLE "public"."user_answer" TO "authenticated";
GRANT ALL ON TABLE "public"."user_answer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_answer_UAID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_answer_UAID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_answer_UAID_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







