-- SIIT Complaint System: core schema (Supabase / PostgreSQL)

CREATE TABLE IF NOT EXISTS public.topic (
    "TopicID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Tname" text NOT NULL,
    CONSTRAINT topic_pkey PRIMARY KEY ("TopicID")
);

CREATE TABLE IF NOT EXISTS public.question (
    "QID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "QText" text,
    "TopicID" bigint,
    CONSTRAINT question_pkey PRIMARY KEY ("QID"),
    CONSTRAINT question_TopicID_fkey FOREIGN KEY ("TopicID")
        REFERENCES public.topic ("TopicID") ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.staff (
    "StaffID" text NOT NULL,
    "UUID" uuid REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    "Division" text,
    "StaffName" text,
    "Email" text,
    CONSTRAINT staff_pkey PRIMARY KEY ("StaffID"),
    CONSTRAINT staff_UUID_key UNIQUE ("UUID"),
    CONSTRAINT staff_Email_key UNIQUE ("Email")
);

CREATE TABLE IF NOT EXISTS public.student (
    "UUID" uuid NOT NULL REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    "StudentID" text NOT NULL,
    "StudentName" text,
    "Year" integer,
    "Department" text,
    "Email" text NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY ("UUID"),
    CONSTRAINT student_StudentID_key UNIQUE ("StudentID"),
    CONSTRAINT student_Email_key UNIQUE ("Email")
);

CREATE TABLE IF NOT EXISTS public.admin (
    "UUID" uuid NOT NULL REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    "Role" text DEFAULT 'Admin'::text NOT NULL,
    "StaffID" text,
    "StudentID" text,
    CONSTRAINT admin_pkey PRIMARY KEY ("UUID"),
    CONSTRAINT admin_StaffID_key UNIQUE ("StaffID"),
    CONSTRAINT admin_StudentID_key UNIQUE ("StudentID"),
    CONSTRAINT admin_StaffID_fkey FOREIGN KEY ("StaffID")
        REFERENCES public.staff ("StaffID") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT admin_StudentID_fkey FOREIGN KEY ("StudentID")
        REFERENCES public.student ("StudentID") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.submission (
    "SubmissionID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "Status" text,
    "StudentID" text,
    "StaffID" text,
    "TopicID" bigint,
    CONSTRAINT submission_pkey PRIMARY KEY ("SubmissionID"),
    CONSTRAINT submission_StaffID_fkey FOREIGN KEY ("StaffID")
        REFERENCES public.staff ("StaffID") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT submission_StudentID_fkey FOREIGN KEY ("StudentID")
        REFERENCES public.student ("StudentID") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT submission_TopicID_fkey FOREIGN KEY ("TopicID")
        REFERENCES public.topic ("TopicID") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_answer (
    "UAID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AnswerText" text,
    "QID" bigint NOT NULL,
    "SubmissionID" bigint NOT NULL,
    "AnsURL" text,
    CONSTRAINT user_answer_pkey PRIMARY KEY ("UAID"),
    CONSTRAINT user_answer_QID_fkey FOREIGN KEY ("QID")
        REFERENCES public.question ("QID") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_answer_SubmissionID_fkey FOREIGN KEY ("SubmissionID")
        REFERENCES public.submission ("SubmissionID") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.resolution (
    "ResID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ResAt" timestamptz DEFAULT now(),
    "ResText" text,
    "ResURL" text,
    "StaffID" text,
    "SubmissionID" bigint NOT NULL,
    CONSTRAINT resolution_pkey PRIMARY KEY ("ResID"),
    CONSTRAINT resolution_StaffID_fkey FOREIGN KEY ("StaffID")
        REFERENCES public.staff ("StaffID") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT resolution_SubmissionID_fkey FOREIGN KEY ("SubmissionID")
        REFERENCES public.submission ("SubmissionID") ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resolution ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_answer ENABLE ROW LEVEL SECURITY;
